/-
XiEpsLocalizedRealization.lean

Localized analytic realization for XiEpsPDE.

Audit rule: `LocalEnergyIdentityData.identity` is never an input.  It is derived
from the tested XiEpsPDE, signed near/far strain splitting, and an integration-
by-parts identity.  Spatial integration and ball averages below are concrete
Mathlib/MeasureTheory definitions.  The remaining differentiation/IBP facts are
kept as primitive analytic hypotheses until their full Sobolev realization is
formalized; this is strictly weaker than assuming the final energy identity.

No CZ estimate, Young inequality, final Campanato/Hölder estimate, enstrophy
supremum, or uniform palinstrophy integral is used.
-/

import G1.XiEpsPDE
import G1.DynamicCampanato

noncomputable section

open MeasureTheory Metric

namespace G1Audit

/-! ## Concrete spatial integration and localization -/

/-- Lebesgue/Bochner integral on R^3. -/
def spatialIntegralScalar (f : ScalarField) : ℝ :=
  ∫ x, f x ∂(volume : Measure Vec3)

/-- Bochner integral of a vector field on R^3. -/
def spatialIntegralVector (f : VectorField) : Vec3 :=
  ∫ x, f x ∂(volume : Measure Vec3)

/-- Volume of the Euclidean ball B_r(c). -/
def ballVolume (r : ℝ) (c : Vec3) : ℝ :=
  volume (Metric.ball c r)

/-- Integral of a vector field over B_r(c). -/
def ballIntegralVector (r : ℝ) (c : Vec3) (f : VectorField) : Vec3 :=
  ∫ x in Metric.ball c r, f x ∂(volume : Measure Vec3)

/--
Concrete ball average.  The zero-volume branch is explicit; all uses in the
Campanato argument carry r>0, so the analytic realization must discharge the
positive-volume branch rather than divide silently by zero.
-/
def avgBallVector (r : ℝ) (c : Vec3) (f : VectorField) : Vec3 :=
  (ballVolume r c)⁻¹ • ballIntegralVector r c f

/-- Weighted scalar integral with the exact XiEps localization weight. -/
def weightedXiIntegral
    (phi mag : ScalarField) (F : ScalarField) : ℝ :=
  spatialIntegralScalar (fun x => (phi x)^2 * mag x * F x)

/--
Concrete localization scale R=K rho_*.  The analytic cutoff itself is supplied
as a scalar field together with derivative-scale certificates below.
-/
structure LocalizedCutoff where
  phi : ScalarField
  K : ℝ
  rho : ℝ
  R : ℝ
  gradScale : ℝ
  lapScale : ℝ
  hK_pos : 0 < K
  hrho_pos : 0 < rho
  hR : R = K * rho
  hgradScale : gradScale = R⁻¹
  hlapScale : lapScale = (R⁻¹)^2

/-- Exact rho_*^{-1} power generated by the cutoff gradient. -/
theorem LocalizedCutoff.grad_rho_power (c : LocalizedCutoff) :
    c.gradScale = (c.K * c.rho)⁻¹ := by
  rw [c.hgradScale, c.hR]

/-- Exact rho_*^{-2} power generated by second cutoff derivatives. -/
theorem LocalizedCutoff.lap_rho_power (c : LocalizedCutoff) :
    c.lapScale = ((c.K * c.rho)⁻¹)^2 := by
  rw [c.hlapScale, c.hR]

/-! ## Primitive differential/IBP realization -/

/--
Differential operators used in the localized PDE test.  `gradScalar` and
`laplacianVector` are operators on actual fields, rather than pre-evaluated
scalar ledger entries.  Their Sobolev/Frechet realization and regularity domain
are the next lower-level formalization target.
-/
structure DifferentialOperators where
  timeDerivScalar : ScalarField → ScalarField
  gradScalar : ScalarField → VectorField
  laplacianVector : VectorField → VectorField

/--
The exact IBP result required for the Laplacian pairing.  This is not the final
LocalEnergyIdentity; it is one primitive analytic theorem about Delta xi tested
against phi^2 (xi-mean) |omega|_eps.
-/
structure DiffusionIBPResult where
  laplacianPair : ℝ
  diffusionBulk : ℝ
  diffusionCutoffCross : ℝ
  diffusionWeightCross : ℝ
  hIBP :
    laplacianPair =
      -diffusionBulk - diffusionCutoffCross - diffusionWeightCross

/-! ## Real signed strain split -/

/-- Scalar kernel used in the signed strain representation. -/
abbrev StrainKernel := Vec3 → Vec3 → ℝ

/--
Near/far decomposition at the real threshold |x-y| = K rho_*.
The kernels themselves are supplied, while `hNearSupport`/`hFarSupport` certify
which geometric region each occupies.
-/
structure StrainSplit where
  kernelTotal : StrainKernel
  kernelNear : StrainKernel
  kernelFar : StrainKernel
  K : ℝ
  rho : ℝ
  R : ℝ
  hK_pos : 0 < K
  hrho_pos : 0 < rho
  hR : R = K * rho
  hSplit : ∀ x y, kernelTotal x y = kernelNear x y + kernelFar x y
  hNearSupport : ∀ x y, R ≤ ‖x - y‖ → kernelNear x y = 0
  hFarSupport : ∀ x y, ‖x - y‖ < R → kernelFar x y = 0

/--
Signed scalar pairings generated by the actual near/far kernels.  No absolute
value or CZ estimate is taken here.
-/
structure StrainPairing where
  total : ℝ
  near : ℝ
  far : ℝ
  hPairSplit : total = near + far

/-! ## Localized XiEps PDE ledger -/

structure XiEpsLocalizedTerms where
  r : ℝ
  rho : ℝ
  K : ℝ
  R : ℝ
  ballVolume : ℝ

  timeEnergyDerivative : ℝ
  timeWeightAndMean : ℝ
  transport : ℝ

  stretchTotal : ℝ
  stretchNear : ℝ
  stretchFar : ℝ

  laplacianPair : ℝ
  diffusionBulk : ℝ
  diffusionCutoffCross : ℝ
  diffusionWeightCross : ℝ
  /-- Includes the factor 2 from 2 grad(log|omega|_eps)·grad xi_eps. -/
  logDrift : ℝ

  R1Pair : ℝ
  R2Pair : ℝ

  hr_pos : 0 < r
  hrho_pos : 0 < rho
  hK_pos : 0 < K
  hR : R = K * rho
  hballVolume_pos : 0 < ballVolume

/--
Analytic realization of the localized XiEpsPDE test.  Crucially there is no
`hIdentity : LocalEnergyIdentityData` field.
-/
structure XiEpsLocalizedRealization where
  pde : XiEpsPDE
  diffOps : DifferentialOperators
  cutoff : LocalizedCutoff
  split : StrainSplit
  pairing : StrainPairing
  ibp : DiffusionIBPResult
  terms : XiEpsLocalizedTerms

  hCutoffR : cutoff.R = terms.R
  hCutoffK : cutoff.K = terms.K
  hCutoffRho : cutoff.rho = terms.rho

  hSplitR : split.R = terms.R
  hSplitK : split.K = terms.K
  hSplitRho : split.rho = terms.rho

  hStretchTotal : terms.stretchTotal = pairing.total
  hStretchNear : terms.stretchNear = pairing.near
  hStretchFar : terms.stretchFar = pairing.far
  hPairingSplit : pairing.total = pairing.near + pairing.far

  hLaplacianPair : terms.laplacianPair = ibp.laplacianPair
  hDiffusionBulk : terms.diffusionBulk = ibp.diffusionBulk
  hDiffusionCutoff : terms.diffusionCutoffCross = ibp.diffusionCutoffCross
  hDiffusionWeight : terms.diffusionWeightCross = ibp.diffusionWeightCross

  /--
  Result of pairing the concrete pointwise XiEpsPDE with
    phi^2 (xi_eps-(xi_eps)_{B_r}) |omega|_eps
  and integrating, BEFORE integration by parts.
  -/
  testedEquation :
    terms.timeEnergyDerivative + terms.timeWeightAndMean + terms.transport =
      terms.stretchTotal
        + pde.ν * terms.laplacianPair
        + pde.ν * terms.logDrift
        + terms.R1Pair + terms.R2Pair

/-- Recover the signed near/far scalar decomposition from the real kernel split. -/
theorem XiEpsLocalizedRealization.strainSplitPair
    (h : XiEpsLocalizedRealization) :
    h.terms.stretchTotal = h.terms.stretchNear + h.terms.stretchFar := by
  rw [h.hStretchTotal, h.hStretchNear, h.hStretchFar]
  exact h.hPairingSplit

/-- Recover the concrete diffusion IBP identity in the term ledger. -/
theorem XiEpsLocalizedRealization.diffusionIBP
    (h : XiEpsLocalizedRealization) :
    h.terms.laplacianPair =
      -h.terms.diffusionBulk
        - h.terms.diffusionCutoffCross
        - h.terms.diffusionWeightCross := by
  rw [h.hLaplacianPair, h.hDiffusionBulk, h.hDiffusionCutoff, h.hDiffusionWeight]
  exact h.ibp.hIBP

/--
The exact LocalEnergyIdentity is now a theorem derived from the tested PDE,
real signed strain split, and diffusion IBP.  No final equality is assumed.
-/
theorem XiEpsLocalizedRealization.localized_identity
    (h : XiEpsLocalizedRealization) :
    h.terms.timeEnergyDerivative
        + h.terms.timeWeightAndMean
        + h.terms.transport
        + h.pde.ν * h.terms.diffusionBulk =
      h.terms.stretchNear + h.terms.stretchFar
        - h.pde.ν * h.terms.diffusionCutoffCross
        - h.pde.ν * h.terms.diffusionWeightCross
        + h.pde.ν * h.terms.logDrift
        + h.terms.R1Pair + h.terms.R2Pair := by
  have hsplit := h.strainSplitPair
  have hibp := h.diffusionIBP
  rw [hsplit] at h.testedEquation
  rw [hibp] at h.testedEquation
  linarith

/-- Build LocalEnergyIdentityData; its identity field is filled by the theorem. -/
def LocalEnergyIdentityData.ofXiEpsPDE
    (h : XiEpsLocalizedRealization) : LocalEnergyIdentityData where
  r := h.terms.r
  rho := h.terms.rho
  K := h.terms.K
  R := h.terms.R
  ballVolume := h.terms.ballVolume
  nu := h.pde.ν
  timeEnergyDerivative := h.terms.timeEnergyDerivative
  timeWeightAndMean := h.terms.timeWeightAndMean
  transport := h.terms.transport
  stretchNear := h.terms.stretchNear
  stretchFar := h.terms.stretchFar
  diffusionBulk := h.terms.diffusionBulk
  diffusionCutoffCross := h.terms.diffusionCutoffCross
  diffusionWeightCross := h.terms.diffusionWeightCross
  logDrift := h.terms.logDrift
  R1 := h.terms.R1Pair
  R2 := h.terms.R2Pair
  hr_pos := h.terms.hr_pos
  hrho_pos := h.terms.hrho_pos
  hK_pos := h.terms.hK_pos
  hnu_pos := h.pde.hν
  hR := h.terms.hR
  hballVolume_pos := h.terms.hballVolume_pos
  identity := h.localized_identity

/-- PROVED_IDENTITY relative only to primitive PDE-test and IBP facts. -/
theorem LocalEnergyIdentityData.ofXiEpsPDE_identity
    (h : XiEpsLocalizedRealization) :
    LocalEnergyIdentity (LocalEnergyIdentityData.ofXiEpsPDE h) := by
  exact (LocalEnergyIdentityData.ofXiEpsPDE h).identity

/-! ## Far-field obstruction and the missing geometric bridge -/

/--
Current local Campanato information yields no positive far-field exponent for
pairs |x-y| >= K rho_*; record the guaranteed exponent exactly as beta=0.
-/
structure FarFieldCampanatoExponentLedger where
  beta : ℝ
  hbeta_zero : beta = 0

/--
Geometric non-degeneracy is an OPEN BRIDGE, not a theorem from dimensional
analysis.  It represents the additional information that an effective active
volume is at least kappa rho_*^3.
-/
structure GeometricNonDegeneracy where
  rho : ℝ
  kappa : ℝ
  effectiveVolume : ℝ
  hrho_pos : 0 < rho
  hkappa_pos : 0 < kappa
  hVolume_nonneg : 0 ≤ effectiveVolume
  volume_lower_bound : kappa * rho^3 ≤ effectiveVolume

/-- Audit status only; no constructor is supplied from XiEpsPDE. -/
inductive XiEpsLocalizedStatus
  | provedIdentity
  | openSignedFarField
  | openGeometricNonDegeneracy
  | blockingScaling
  deriving DecidableEq, Repr

end G1Audit
